/** ****************************************************************************
 * @file   main.c
 * 
 * @author Michael R.
 * 
 * @brief 
 * 
 * @date   2023-07-30
 **************************************************************************** */

/* --- Includes ------------------------------------------------------------- */
#include <stdio.h>

#include "project_conf.h"  /* Generated by CMake from project_conf.h.in */

#include "lib1/lib1.h"
#include "lib2/lib2.h"


/* --- Local macro definitions ---------------------------------------------- */


/* --- Local type/struct definitions ---------------------------------------- */


/* --- Static variables ----------------------------------------------------- */


/* --- Static function prototypes ------------------------------------------- */


/* --- Public functions ----------------------------------------------------- */

int main(void)
{
    printf("Hello World (main.c)\n");
    printf("Version = %d.%d.%d\n", 
        PROJECT_VERSION_MAJOR, 
        PROJECT_VERSION_MINOR, 
        PROJECT_VERSION_PATCH);

    vLib1Main();
    vLib2Main();

    return(0);
    
}

/* --- Static functions ----------------------------------------------------- */

